In [16]:
# Data\ValueUp
# 1.marketcap
# 2.fundamentals
# 3.dividends

# 폴더 이름
# 1. marketcap
 # 칼럼 명 : stockcode,avg_marcap,avg_amount,Name,Market,Stocks
# 2. fundamentals
 # 날짜,BPS,PER,PBR,EPS,DIV,DPS,Year,stockcode,Name,Market,년도
# 3. dividends
 # stockcode,Name,Market,Stocks,avg_marcap,avg_amount,2018_배당,2018_자사주,2019_배당,2019_자사주,최근2년_활동

# 라이브러리 호출
import pandas as pd
import numpy as np
import os

marketcap = pd.read_csv('../Data/ValueUp/1.marketcap/cap_2018.csv')
marketcap

year = list(range(2018, 2025))

# 메타 데이터 추출을 위해 모든 데이터 병합

marketcap_list = []
for year in year:
    marketcap = pd.read_csv('../Data/ValueUp/1.marketcap/cap_{}.csv'.format(year))
    marketcap_list.append(marketcap)

marketcap_list

# 데이터 병합
marketcap_all = pd.concat(marketcap_list, axis=0)

marketcap_all

     stockcode    avg_marcap    avg_amount        Name  Market      Stocks
0      A005930  2.994495e+14  5.985881e+11        삼성전자   KOSPI  5969782550
1      A000660  5.711119e+13  2.990335e+11      SK하이닉스   KOSPI   728002365
2      A068270  3.434068e+13  3.795301e+11        셀트리온  KOSDAQ   125456133
3      A005380  2.935432e+13  7.596154e+10         현대차   KOSPI   213668187
4      A207940  2.879188e+13  1.315133e+11    삼성바이오로직스   KOSPI    66165000
...        ...           ...           ...         ...     ...         ...
2474   A053590  1.795887e+09  8.086590e+08     한국테크놀로지  KOSDAQ   157140147
2475   A114120  1.237943e+09  8.016716e+08        크루셜텍  KOSDAQ     2296131
2476   A263540  8.862336e+08  6.243926e+08  어스앤에어로스페이스  KOSDAQ    14294091
2477   A030790  8.559967e+08  5.367534e+08       비케이탑스   KOSPI    21248145
2478   A141020  2.574117e+08  3.643128e+08       디에스앤엘  KOSDAQ    11700533

[15874 rows x 6 columns]

In [27]:
# 시가총액 기준으로 정렬하고 종목코드 중복 제거
stock_code = marketcap_all.sort_values(['avg_marcap', 'avg_amount'], ascending=[False, False])

# stocode 별로 하나 씩만 남기기
stock_code = stock_code.drop_duplicates(subset=['stockcode'])

# 종목코드 출력
stock_code

# 인덱스 리셋
stock_code = stock_code.reset_index(drop=True)

# 종목코드 출력
stock_code.to_csv('../Data/metadata.csv', index=False)